name: 'gauron custom GH action'
description: 'This action does custom stuff for it is custom'
inputs:
  os:
    description: 'Operating System you want to download binary for(exact string expected), otherwise will be determined via the GH Runner'
  version:
    description: 'Provide version to download using the "knative-" prefix version'
    default: 'v1.16.1' #default to latest -- must be updated
outputs:
  time:
    description: 'Time of execution'
runs:
  using: 'node16'
  main: 'index.js'
