name: 'gauron custom GH action'
description: 'This action does custom stuff for it is custom'
inputs:
  name:
    description: '(optional) Name of the Function binary (defaults to "func"'
  binary:
    description: '(optional) Binary you want to download (exact string expected), otherwise will be determined via the OS of GH Runner'
  version:
    description: '(optional) Provide version to download'
  destination:
    description: '(optional) Provide a path where to move the desired downloaded binary, otherwise cwd is used'
runs:
  using: 'node20'
  main: 'index.js'
